"""create blog_comments table

Revision ID: 027be9cdfbf8
Revises: 8cefc705fbed
Create Date: 2026-10-05 22:19:28.802773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '027be9cdfbf8'
down_revision: Union[str, Sequence[str], None] = '8cefc705fbed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_posts', 'tags',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               nullable=False,
               existing_server_default=sa.text("'[]'::text"))
    op.alter_column('blog_posts', 'views_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('blog_posts', 'likes_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('blog_posts', 'dislikes_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_posts', 'dislikes_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('blog_posts', 'likes_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('blog_posts', 'views_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('blog_posts', 'tags',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'[]'::text"))
    # ### end Alembic commands ###
