"""create blog_comments table

Revision ID: 027be9cdfbf8
Revises: 8cefc705fbed
Create Date: 2026-10-05 22:19:28.802773

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '027be9cdfbf8'
down_revision: Union[str, Sequence[str], None] = '8cefc705fbed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('blog_posts', sa.Column('tags', sa.JSON(), server_default='[]', nullable=False))
    op.add_column('blog_posts', sa.Column('views_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('blog_posts', sa.Column('likes_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('blog_posts', sa.Column('dislikes_count', sa.Integer(), server_default='0', nullable=False))

    op.create_table('blog_comments',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('post_id', sa.UUID(), nullable=False),
        sa.Column('parent_id', sa.UUID(), nullable=True),
        sa.Column('user_id', sa.UUID(), nullable=True),
        sa.Column('guest_name', sa.String(length=255), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False, server_default='pending'),
        sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(['parent_id'], ['blog_comments.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['post_id'], ['blog_posts.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='SET NULL'),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blog_comments_post_id'), 'blog_comments', ['post_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_blog_comments_post_id'), table_name='blog_comments')
    op.drop_table('blog_comments')
    
    op.drop_column('blog_posts', 'dislikes_count')
    op.drop_column('blog_posts', 'likes_count')
    op.drop_column('blog_posts', 'views_count')
    op.drop_column('blog_posts', 'tags')
    # ### end Alembic commands ###
