"""Add name and description to waitlist_whitelist

Revision ID: 05ac7687bc07
Revises: 1a01de8fca63
Create Date: 2026-09-16 14:24:39.376426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '05ac7687bc07'
down_revision: Union[str, Sequence[str], None] = '1a01de8fca63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitlist_whitelist', sa.Column('name', sa.String(), nullable=True))
    op.add_column('waitlist_whitelist', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('waitlist_whitelist', 'description')
    op.drop_column('waitlist_whitelist', 'name')
    # ### end Alembic commands ###
