"""waitlist mode

Revision ID: 1a01de8fca63
Revises: 1dafdf6a3f19
Create Date: 2026-09-16 12:40:55.426025

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a01de8fca63'
down_revision: Union[str, Sequence[str], None] = '1dafdf6a3f19'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('waitlist_whitelist',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('identifier_type', sa.Enum('EMAIL', 'PHONE', name='identifiertype'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_waitlist_whitelist_identifier'), 'waitlist_whitelist', ['identifier'], unique=True)
    op.add_column('users', sa.Column('is_waitlisted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_waitlisted')
    op.drop_index(op.f('ix_waitlist_whitelist_identifier'), table_name='waitlist_whitelist')
    op.drop_table('waitlist_whitelist')
    # ### end Alembic commands ###
