"""add_original_transaction_code

Revision ID: 1ad33ae1f4c4
Revises: ba3fa1e4e85c
Create Date: 2026-09-04 22:40:15.375734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1ad33ae1f4c4'
down_revision: Union[str, Sequence[str], None] = 'ba3fa1e4e85c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('original_transaction_code', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'original_transaction_code')
    # ### end Alembic commands ###
