"""Add active_sessions_count to system_metrics

Revision ID: 1dafdf6a3f19
Revises: ee7b4825c1a7
Create Date: 2026-09-15 02:30:53.980589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dafdf6a3f19'
down_revision: Union[str, Sequence[str], None] = 'ee7b4825c1a7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('system_metrics', sa.Column('active_sessions_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('system_metrics', 'active_sessions_count')
    # ### end Alembic commands ###
