"""Add is_split and notes to transaction

Revision ID: 21645580aa6c
Revises: ae190b7884e9
Create Date: 2026-08-27 13:57:55.906019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '21645580aa6c'
down_revision: Union[str, Sequence[str], None] = 'ae190b7884e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('is_split', sa.Boolean(), nullable=True))
    op.add_column('transactions', sa.Column('notes', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'notes')
    op.drop_column('transactions', 'is_split')
    # ### end Alembic commands ###
