"""Employee management

Revision ID: 2ddcfebfca7f
Revises: d4e6a9b3c5f7
Create Date: 2026-10-08 11:42:36.448219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2ddcfebfca7f'
down_revision: Union[str, Sequence[str], None] = 'd4e6a9b3c5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius_meters', sa.Integer(), nullable=False),
    sa.Column('is_default', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('uq_work_locations_default', 'work_locations', ['is_default'], unique=True, postgresql_where=sa.text('is_default'), sqlite_where=sa.text('is_default'))
    op.create_table('attendance_adjustments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('clock_in_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clock_out_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('adjusted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['adjusted_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_attendance_adjustment_user_date')
    )
    op.create_index(op.f('ix_attendance_adjustments_date'), 'attendance_adjustments', ['date'], unique=False)
    op.create_index(op.f('ix_attendance_adjustments_user_id'), 'attendance_adjustments', ['user_id'], unique=False)
    op.create_table('work_schedule_days',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('weekday', sa.Integer(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('cutoff_time', sa.Time(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'weekday', name='uq_work_schedule_user_weekday')
    )
    op.create_index(op.f('ix_work_schedule_days_user_id'), 'work_schedule_days', ['user_id'], unique=False)
    op.create_index('uq_work_schedule_company_weekday', 'work_schedule_days', ['weekday'], unique=True, postgresql_where=sa.text('user_id IS NULL'), sqlite_where=sa.text('user_id IS NULL'))
    op.create_table('work_schedule_overrides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('mode', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=True),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['location_id'], ['work_locations.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'date', name='uq_work_schedule_override_user_date')
    )
    op.create_index(op.f('ix_work_schedule_overrides_date'), 'work_schedule_overrides', ['date'], unique=False)
    op.create_index(op.f('ix_work_schedule_overrides_user_id'), 'work_schedule_overrides', ['user_id'], unique=False)
    op.create_index('uq_work_schedule_override_company_date', 'work_schedule_overrides', ['date'], unique=True, postgresql_where=sa.text('user_id IS NULL'), sqlite_where=sa.text('user_id IS NULL'))
    op.alter_column(
        'blog_posts',
        'tags',
        existing_type=sa.TEXT(),
        server_default=None,
    )
    op.alter_column(
        'blog_posts',
        'tags',
        existing_type=sa.TEXT(),
        type_=sa.JSON(),
        nullable=False,
        postgresql_using='tags::json',
    )
    op.alter_column(
        'blog_posts',
        'tags',
        existing_type=sa.JSON(),
        server_default=sa.text("'[]'::json"),
    )
    op.alter_column('blog_posts', 'views_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('blog_posts', 'likes_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('blog_posts', 'dislikes_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('employee_reports', sa.Column('is_late', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('meeting_attendees', sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('meeting_attendees', sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('meeting_attendees', sa.Column('checkin_latitude', sa.String(), nullable=True))
    op.add_column('meeting_attendees', sa.Column('checkin_longitude', sa.String(), nullable=True))
    op.add_column('meeting_attendees', sa.Column('marked_by', sa.UUID(), nullable=True))
    op.add_column('meeting_attendees', sa.Column('reminder_24h_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('meeting_attendees', sa.Column('reminder_1h_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('meeting_attendees', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_meeting_attendees_meeting_id'), 'meeting_attendees', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_attendees_user_id'), 'meeting_attendees', ['user_id'], unique=False)
    op.create_unique_constraint('uq_meeting_attendee', 'meeting_attendees', ['meeting_id', 'user_id'])
    op.create_foreign_key(None, 'meeting_attendees', 'users', ['marked_by'], ['user_id'])
    op.add_column('meetings', sa.Column('location_id', sa.UUID(), nullable=True))
    op.add_column('meetings', sa.Column('status', sa.String(), server_default='scheduled', nullable=False))
    op.add_column('meetings', sa.Column('audience', sa.String(), server_default='custom', nullable=False))
    op.add_column('meetings', sa.Column('audience_roles', sa.JSON(), nullable=True))
    op.add_column('meetings', sa.Column('attendance_finalized_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('meetings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.create_foreign_key(None, 'meetings', 'work_locations', ['location_id'], ['id'], ondelete='SET NULL')
    op.add_column('users', sa.Column('sessions_revoked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sessions_revoked_at')
    op.drop_constraint(None, 'meetings', type_='foreignkey')
    op.drop_column('meetings', 'updated_at')
    op.drop_column('meetings', 'attendance_finalized_at')
    op.drop_column('meetings', 'audience_roles')
    op.drop_column('meetings', 'audience')
    op.drop_column('meetings', 'status')
    op.drop_column('meetings', 'location_id')
    op.drop_constraint(None, 'meeting_attendees', type_='foreignkey')
    op.drop_constraint('uq_meeting_attendee', 'meeting_attendees', type_='unique')
    op.drop_index(op.f('ix_meeting_attendees_user_id'), table_name='meeting_attendees')
    op.drop_index(op.f('ix_meeting_attendees_meeting_id'), table_name='meeting_attendees')
    op.drop_column('meeting_attendees', 'created_at')
    op.drop_column('meeting_attendees', 'reminder_1h_sent_at')
    op.drop_column('meeting_attendees', 'reminder_24h_sent_at')
    op.drop_column('meeting_attendees', 'marked_by')
    op.drop_column('meeting_attendees', 'checkin_longitude')
    op.drop_column('meeting_attendees', 'checkin_latitude')
    op.drop_column('meeting_attendees', 'checked_in_at')
    op.drop_column('meeting_attendees', 'responded_at')
    op.drop_column('employee_reports', 'is_late')
    op.alter_column('blog_posts', 'dislikes_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('blog_posts', 'likes_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('blog_posts', 'views_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column(
        'blog_posts',
        'tags',
        existing_type=sa.JSON(),
        server_default=None,
    )
    op.alter_column(
        'blog_posts',
        'tags',
        existing_type=sa.JSON(),
        type_=sa.TEXT(),
        nullable=True,
        postgresql_using='tags::text',
    )
    op.alter_column(
        'blog_posts',
        'tags',
        existing_type=sa.TEXT(),
        server_default=sa.text("'[]'::text"),
    )
    op.drop_index('uq_work_schedule_override_company_date', table_name='work_schedule_overrides', postgresql_where=sa.text('user_id IS NULL'), sqlite_where=sa.text('user_id IS NULL'))
    op.drop_index(op.f('ix_work_schedule_overrides_user_id'), table_name='work_schedule_overrides')
    op.drop_index(op.f('ix_work_schedule_overrides_date'), table_name='work_schedule_overrides')
    op.drop_table('work_schedule_overrides')
    op.drop_index('uq_work_schedule_company_weekday', table_name='work_schedule_days', postgresql_where=sa.text('user_id IS NULL'), sqlite_where=sa.text('user_id IS NULL'))
    op.drop_index(op.f('ix_work_schedule_days_user_id'), table_name='work_schedule_days')
    op.drop_table('work_schedule_days')
    op.drop_index(op.f('ix_attendance_adjustments_user_id'), table_name='attendance_adjustments')
    op.drop_index(op.f('ix_attendance_adjustments_date'), table_name='attendance_adjustments')
    op.drop_table('attendance_adjustments')
    op.drop_index('uq_work_locations_default', table_name='work_locations', postgresql_where=sa.text('is_default'), sqlite_where=sa.text('is_default'))
    op.drop_table('work_locations')
    # ### end Alembic commands ###
