"""Employee management

Revision ID: 2ddcfebfca7f
Revises: d4e6a9b3c5f7
Create Date: 2026-10-08 11:42:36.448219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2ddcfebfca7f'
down_revision: Union[str, Sequence[str], None] = 'd4e6a9b3c5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'blog_posts',
        'tags',
        existing_type=sa.TEXT(),
        server_default=None,
    )
    op.alter_column(
        'blog_posts',
        'tags',
        existing_type=sa.TEXT(),
        type_=sa.JSON(),
        nullable=False,
        postgresql_using='tags::json',
    )
    op.alter_column(
        'blog_posts',
        'tags',
        existing_type=sa.JSON(),
        server_default=sa.text("'[]'::json"),
    )
    op.alter_column('blog_posts', 'views_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('blog_posts', 'likes_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('blog_posts', 'dislikes_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blog_posts', 'dislikes_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('blog_posts', 'likes_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('blog_posts', 'views_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column(
        'blog_posts',
        'tags',
        existing_type=sa.JSON(),
        server_default=None,
    )
    op.alter_column(
        'blog_posts',
        'tags',
        existing_type=sa.JSON(),
        type_=sa.TEXT(),
        nullable=True,
        postgresql_using='tags::text',
    )
    op.alter_column(
        'blog_posts',
        'tags',
        existing_type=sa.TEXT(),
        server_default=sa.text("'[]'::text"),
    )
    # ### end Alembic commands ###
