"""Employee management

Revision ID: 2ddcfebfca7f
Revises: d4e6a9b3c5f7
Create Date: 2026-10-08 11:42:36.448219

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = '2ddcfebfca7f'
down_revision: Union[str, Sequence[str], None] = 'd4e6a9b3c5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        'blog_posts',
        'tags',
        existing_type=sa.TEXT(),
        server_default=None,
    )
    op.alter_column(
        'blog_posts',
        'tags',
        existing_type=sa.TEXT(),
        type_=sa.JSON(),
        nullable=False,
        postgresql_using='tags::json',
    )
    op.alter_column(
        'blog_posts',
        'tags',
        existing_type=sa.JSON(),
        server_default=sa.text("'[]'::json"),
    )
    op.alter_column('blog_posts', 'views_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('blog_posts', 'likes_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('blog_posts', 'dislikes_count',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.add_column('employee_reports', sa.Column('is_late', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('meeting_attendees', sa.Column('responded_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('meeting_attendees', sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('meeting_attendees', sa.Column('checkin_latitude', sa.String(), nullable=True))
    op.add_column('meeting_attendees', sa.Column('checkin_longitude', sa.String(), nullable=True))
    op.add_column('meeting_attendees', sa.Column('marked_by', sa.UUID(), nullable=True))
    op.add_column('meeting_attendees', sa.Column('reminder_24h_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('meeting_attendees', sa.Column('reminder_1h_sent_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('meeting_attendees', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    op.create_index(op.f('ix_meeting_attendees_meeting_id'), 'meeting_attendees', ['meeting_id'], unique=False)
    op.create_index(op.f('ix_meeting_attendees_user_id'), 'meeting_attendees', ['user_id'], unique=False)
    op.create_unique_constraint('uq_meeting_attendee', 'meeting_attendees', ['meeting_id', 'user_id'])
    op.create_foreign_key(None, 'meeting_attendees', 'users', ['marked_by'], ['user_id'])
    op.add_column('meetings', sa.Column('status', sa.String(), server_default='scheduled', nullable=False))
    op.add_column('meetings', sa.Column('audience', sa.String(), server_default='custom', nullable=False))
    op.add_column('meetings', sa.Column('audience_roles', sa.JSON(), nullable=True))
    op.add_column('meetings', sa.Column('attendance_finalized_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('meetings', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('sessions_revoked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'sessions_revoked_at')
    op.drop_column('meetings', 'updated_at')
    op.drop_column('meetings', 'attendance_finalized_at')
    op.drop_column('meetings', 'audience_roles')
    op.drop_column('meetings', 'audience')
    op.drop_column('meetings', 'status')
    op.drop_constraint(None, 'meeting_attendees', type_='foreignkey')
    op.drop_constraint('uq_meeting_attendee', 'meeting_attendees', type_='unique')
    op.drop_index(op.f('ix_meeting_attendees_user_id'), table_name='meeting_attendees')
    op.drop_index(op.f('ix_meeting_attendees_meeting_id'), table_name='meeting_attendees')
    op.drop_column('meeting_attendees', 'created_at')
    op.drop_column('meeting_attendees', 'reminder_1h_sent_at')
    op.drop_column('meeting_attendees', 'reminder_24h_sent_at')
    op.drop_column('meeting_attendees', 'marked_by')
    op.drop_column('meeting_attendees', 'checkin_longitude')
    op.drop_column('meeting_attendees', 'checkin_latitude')
    op.drop_column('meeting_attendees', 'checked_in_at')
    op.drop_column('meeting_attendees', 'responded_at')
    op.drop_column('employee_reports', 'is_late')
    op.alter_column('blog_posts', 'dislikes_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('blog_posts', 'likes_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('blog_posts', 'views_count',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column(
        'blog_posts',
        'tags',
        existing_type=sa.JSON(),
        server_default=None,
    )
    op.alter_column(
        'blog_posts',
        'tags',
        existing_type=sa.JSON(),
        type_=sa.TEXT(),
        nullable=True,
        postgresql_using='tags::text',
    )
    op.alter_column(
        'blog_posts',
        'tags',
        existing_type=sa.TEXT(),
        server_default=sa.text("'[]'::text"),
    )
    # ### end Alembic commands ###
