"""add hr gps fields

Revision ID: 614f92b1b470
Revises: a8276c7389e5
Create Date: 2026-10-07 17:19:07.538051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '614f92b1b470'
down_revision: Union[str, Sequence[str], None] = 'a8276c7389e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employee_reports', sa.Column('work_mode', sa.String(), server_default='physical', nullable=False))
    op.add_column('employee_reports', sa.Column('latitude', sa.String(), nullable=True))
    op.add_column('employee_reports', sa.Column('longitude', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employee_reports', 'longitude')
    op.drop_column('employee_reports', 'latitude')
    op.drop_column('employee_reports', 'work_mode')
    # ### end Alembic commands ###
