"""Add WhatsAppBlocklist

Revision ID: 620814ff5cca
Revises: add_short_code
Create Date: 2026-08-20 21:56:32.785627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '620814ff5cca'
down_revision: Union[str, Sequence[str], None] = 'add_short_code'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('whatsapp_blocklist',
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('last_attempt_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('phone_number')
    )
    op.create_index(op.f('ix_whatsapp_blocklist_phone_number'), 'whatsapp_blocklist', ['phone_number'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('related_entity_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index('idx_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.add_column('campaigns', sa.Column('short_code', sa.String(length=8), nullable=True))
    op.create_index(op.f('ix_campaigns_short_code'), 'campaigns', ['short_code'], unique=True)
    op.add_column('pending_transactions', sa.Column('processed_at', sa.DateTime(), nullable=True))
    op.add_column('pending_transactions', sa.Column('processed_by', sa.UUID(), nullable=True))
    op.add_column('pending_transactions', sa.Column('rejection_reason', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pending_transactions', 'rejection_reason')
    op.drop_column('pending_transactions', 'processed_by')
    op.drop_column('pending_transactions', 'processed_at')
    op.drop_index(op.f('ix_campaigns_short_code'), table_name='campaigns')
    op.drop_column('campaigns', 'short_code')
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.drop_index('idx_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_whatsapp_blocklist_phone_number'), table_name='whatsapp_blocklist')
    op.drop_table('whatsapp_blocklist')
    # ### end Alembic commands ###
