"""add profile_picture_url

Revision ID: 8093f7c8baa3
Revises: 1cbd32e97c2e
Create Date: 2026-10-03 22:17:23.493271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8093f7c8baa3'
down_revision: Union[str, Sequence[str], None] = '1cbd32e97c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
