"""Add transaction_type to SubscriptionPayment

Revision ID: 8a7fadbb158c
Revises: ca3b947dba2b
Create Date: 2026-08-24 17:14:43.118571

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8a7fadbb158c'
down_revision: Union[str, Sequence[str], None] = 'ca3b947dba2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_payments', sa.Column('transaction_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_payments', 'transaction_type')
    # ### end Alembic commands ###
