"""Add permissions column to users and employee_invites

Revision ID: 8cefc705fbed
Revises: 04de000a399e
Create Date: 2026-10-04 20:49:02.879230

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cefc705fbed'
down_revision: Union[str, Sequence[str], None] = '04de000a399e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.add_column('employee_invites', sa.Column('permissions', sa.JSON(), nullable=True))
    op.add_column('users', sa.Column('permissions', sa.JSON(), nullable=True))

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permissions')
    op.drop_column('employee_invites', 'permissions')
    # ### end Alembic commands ###
