"""refactor_whitelist_person_record

Revision ID: 95588c0ab1a7
Revises: 05ac7687bc07
Create Date: 2026-09-16 19:11:07.825856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95588c0ab1a7'
down_revision: Union[str, Sequence[str], None] = '05ac7687bc07'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DELETE FROM waitlist_whitelist")
    op.add_column('waitlist_whitelist', sa.Column('phone_number', sa.String(), nullable=False))
    op.add_column('waitlist_whitelist', sa.Column('email', sa.String(), nullable=False))
    op.add_column('waitlist_whitelist', sa.Column('invite_sent', sa.Boolean(), nullable=False))
    op.drop_index(op.f('ix_waitlist_whitelist_identifier'), table_name='waitlist_whitelist')
    op.create_index(op.f('ix_waitlist_whitelist_email'), 'waitlist_whitelist', ['email'], unique=True)
    op.create_index(op.f('ix_waitlist_whitelist_phone_number'), 'waitlist_whitelist', ['phone_number'], unique=True)
    op.drop_column('waitlist_whitelist', 'identifier_type')
    op.drop_column('waitlist_whitelist', 'identifier')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('waitlist_whitelist', sa.Column('identifier', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('waitlist_whitelist', sa.Column('identifier_type', postgresql.ENUM('EMAIL', 'PHONE', name='identifiertype'), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_waitlist_whitelist_phone_number'), table_name='waitlist_whitelist')
    op.drop_index(op.f('ix_waitlist_whitelist_email'), table_name='waitlist_whitelist')
    op.create_index(op.f('ix_waitlist_whitelist_identifier'), 'waitlist_whitelist', ['identifier'], unique=True)
    op.drop_column('waitlist_whitelist', 'invite_sent')
    op.drop_column('waitlist_whitelist', 'email')
    op.drop_column('waitlist_whitelist', 'phone_number')
    # ### end Alembic commands ###
