"""Add has_used_trial to users

Revision ID: ae190b7884e9
Revises: 8a7fadbb158c
Create Date: 2026-08-24 21:01:32.669931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae190b7884e9'
down_revision: Union[str, Sequence[str], None] = '8a7fadbb158c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('has_used_trial', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_used_trial')
    # ### end Alembic commands ###
