"""isolate_transaction_codes

Revision ID: aec8c929ff85
Revises: e291751da8fb
Create Date: 2026-07-01 23:27:25.302137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'aec8c929ff85'
down_revision: Union[str, Sequence[str], None] = 'e291751da8fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('pending_transactions_transaction_code_key'), 'pending_transactions', type_='unique')
    op.create_unique_constraint('uix_pending_owner_txn_code', 'pending_transactions', ['owner_id', 'transaction_code'])
    op.drop_constraint(op.f('transactions_transaction_code_key'), 'transactions', type_='unique')
    op.create_unique_constraint('uix_owner_txn_code', 'transactions', ['owner_id', 'transaction_code'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_owner_txn_code', 'transactions', type_='unique')
    op.create_unique_constraint(op.f('transactions_transaction_code_key'), 'transactions', ['transaction_code'], postgresql_nulls_not_distinct=False)
    op.drop_constraint('uix_pending_owner_txn_code', 'pending_transactions', type_='unique')
    op.create_unique_constraint(op.f('pending_transactions_transaction_code_key'), 'pending_transactions', ['transaction_code'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
