"""Add slugs, favorites, and end dates

Revision ID: b35a08a14531
Revises: f9b8c7d6e5a4
Create Date: 2026-07-25 20:17:15.216005

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b35a08a14531'
down_revision: Union[str, Sequence[str], None] = 'f9b8c7d6e5a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_learning_samples',
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('is_consumed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_table('token_blacklist',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    op.add_column('campaigns', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    op.add_column('campaigns', sa.Column('end_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_campaigns_slug'), 'campaigns', ['slug'], unique=False)
    op.create_unique_constraint('uq_campaign_group_slug', 'campaigns', ['group_id', 'slug'])
    op.add_column('groups', sa.Column('slug', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_groups_slug'), 'groups', ['slug'], unique=False)
    op.create_unique_constraint('uq_group_owner_slug', 'groups', ['owner_id', 'slug'])
    op.drop_column('pending_transactions', 'evidence_url')
    op.drop_column('transactions', 'evidence_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('evidence_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('pending_transactions', sa.Column('evidence_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint('uq_group_owner_slug', 'groups', type_='unique')
    op.drop_index(op.f('ix_groups_slug'), table_name='groups')
    op.drop_column('groups', 'is_favorite')
    op.drop_column('groups', 'slug')
    op.drop_constraint('uq_campaign_group_slug', 'campaigns', type_='unique')
    op.drop_index(op.f('ix_campaigns_slug'), table_name='campaigns')
    op.drop_column('campaigns', 'end_date')
    op.drop_column('campaigns', 'is_favorite')
    op.drop_column('campaigns', 'slug')
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_table('active_learning_samples')
    # ### end Alembic commands ###
