"""add support session ratings

Revision ID: b7ccd606199f
Revises: 68ed9ad6b862
Create Date: 2026-08-24 10:39:16.067191

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7ccd606199f'
down_revision: Union[str, Sequence[str], None] = '68ed9ad6b862'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_session_ratings',
    sa.Column('rating_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('issue_resolved', sa.Boolean(), nullable=False),
    sa.Column('satisfaction_level', sa.Integer(), nullable=False),
    sa.Column('response_quality', sa.Integer(), nullable=True),
    sa.Column('response_speed', sa.Integer(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.ticket_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('rating_id'),
    sa.UniqueConstraint('ticket_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('support_session_ratings')
    # ### end Alembic commands ###
