"""Add marketing_consent

Revision ID: ba3fa1e4e85c
Revises: b3390ebd6a96
Create Date: 2026-08-28 13:58:35.785910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ba3fa1e4e85c'
down_revision: Union[str, Sequence[str], None] = 'b3390ebd6a96'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('marketing_consent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'marketing_consent')
    # ### end Alembic commands ###
