"""Add payment_metadata to SubscriptionPayment

Revision ID: ca3b947dba2b
Revises: b7ccd606199f
Create Date: 2026-08-24 16:37:57.578240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca3b947dba2b'
down_revision: Union[str, Sequence[str], None] = 'b7ccd606199f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription_payments', sa.Column('payment_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription_payments', 'payment_metadata')
    # ### end Alembic commands ###
