"""Add SupportTicketMessage and SLA fields

Revision ID: cb5b9ad36e64
Revises: a1b2c3d4e5f7
Create Date: 2026-08-23 22:09:31.087153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb5b9ad36e64'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('support_ticket_messages',
    sa.Column('message_id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('sender_id', sa.UUID(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_internal', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['sender_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['support_tickets.ticket_id'], ),
    sa.PrimaryKeyConstraint('message_id')
    )
    op.drop_index(op.f('ix_app_feedback_created_at'), table_name='app_feedback')
    op.drop_index(op.f('ix_app_feedback_feedback_type'), table_name='app_feedback')
    op.drop_index(op.f('ix_app_feedback_status'), table_name='app_feedback')
    op.add_column('support_tickets', sa.Column('sla_deadline', sa.DateTime(), nullable=True))
    op.add_column('support_tickets', sa.Column('last_reply_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('support_tickets', 'last_reply_at')
    op.drop_column('support_tickets', 'sla_deadline')
    op.create_index(op.f('ix_app_feedback_status'), 'app_feedback', ['status'], unique=False)
    op.create_index(op.f('ix_app_feedback_feedback_type'), 'app_feedback', ['feedback_type'], unique=False)
    op.create_index(op.f('ix_app_feedback_created_at'), 'app_feedback', ['created_at'], unique=False)
    op.drop_table('support_ticket_messages')
    # ### end Alembic commands ###
