"""add campaign_id to communication_logs

Revision ID: cfabe170f61d
Revises: 325888e3300c
Create Date: 2026-09-12 14:45:27.888888

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cfabe170f61d'
down_revision: Union[str, Sequence[str], None] = '325888e3300c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('communication_logs', sa.Column('campaign_id', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('communication_logs', 'campaign_id')
    # ### end Alembic commands ###
