"""Add custom auth models

Revision ID: e291751da8fb
Revises: 331c3d2d1609
Create Date: 2026-07-01 12:48:44.496255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e291751da8fb'
down_revision: Union[str, Sequence[str], None] = '331c3d2d1609'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system_configs',
    sa.Column('config_key', sa.String(), nullable=False),
    sa.Column('config_value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('config_key')
    )
    op.create_table('otps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscription_payments',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('provider_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.subscription_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.add_column('campaigns', sa.Column('description', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('payment_instructions', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('status', sa.String(), nullable=True))
    op.add_column('campaigns', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('campaigns', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_campaigns_group_id'), 'campaigns', ['group_id'], unique=False)
    op.add_column('groups', sa.Column('group_name', sa.String(), nullable=False, server_default='Unknown'))
    op.add_column('groups', sa.Column('description', sa.String(), nullable=True))
    op.add_column('groups', sa.Column('currency', sa.String(length=3), nullable=True))
    op.add_column('groups', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_groups_owner_id'), 'groups', ['owner_id'], unique=False)
    op.drop_column('groups', 'name')
    op.add_column('pending_transactions', sa.Column('original_ai_output', sa.JSON(), nullable=True))
    op.add_column('pending_transactions', sa.Column('evidence_url', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('sender_name', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('ledger_hash', sa.String(), nullable=True))
    op.add_column('transactions', sa.Column('evidence_url', sa.String(), nullable=True))
    op.add_column('users', sa.Column('first_name', sa.String(), nullable=False, server_default='Unknown'))
    op.add_column('users', sa.Column('last_name', sa.String(), nullable=False, server_default='Unknown'))
    op.add_column('users', sa.Column('hashed_password', sa.String(), nullable=True))
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phone_number_verified', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('allow_ai_training', sa.Boolean(), nullable=True))
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'allow_ai_training')
    op.drop_column('users', 'phone_number_verified')
    op.drop_column('users', 'email_verified')
    op.drop_column('users', 'hashed_password')
    op.drop_column('users', 'last_name')
    op.drop_column('users', 'first_name')
    op.drop_column('transactions', 'evidence_url')
    op.drop_column('transactions', 'ledger_hash')
    op.drop_column('transactions', 'sender_name')
    op.drop_column('pending_transactions', 'evidence_url')
    op.drop_column('pending_transactions', 'original_ai_output')
    op.add_column('groups', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_groups_owner_id'), table_name='groups')
    op.drop_column('groups', 'is_active')
    op.drop_column('groups', 'currency')
    op.drop_column('groups', 'description')
    op.drop_column('groups', 'group_name')
    op.drop_index(op.f('ix_campaigns_group_id'), table_name='campaigns')
    op.drop_column('campaigns', 'created_at')
    op.drop_column('campaigns', 'is_active')
    op.drop_column('campaigns', 'status')
    op.drop_column('campaigns', 'payment_instructions')
    op.drop_column('campaigns', 'description')
    op.drop_table('subscription_payments')
    op.drop_table('otps')
    op.drop_table('system_configs')
    # ### end Alembic commands ###
