"""additions of more models

Revision ID: e70212aba69d
Revises: 9e2b7d4c1a63
Create Date: 2026-10-08 15:27:37.153047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e70212aba69d'
down_revision: Union[str, Sequence[str], None] = '9e2b7d4c1a63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_invoices_status_issued'), table_name='invoices')
    op.drop_index(op.f('ix_subscription_payments_provider_reference'), table_name='subscription_payments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_subscription_payments_provider_reference'), 'subscription_payments', ['provider_reference'], unique=False)
    op.create_index(op.f('ix_invoices_status_issued'), 'invoices', ['status', 'issued_at'], unique=False)
    # ### end Alembic commands ###
