"""Initial Schema

Revision ID: ee7f2a5d3f2a
Revises: 
Create Date: 2026-08-14 20:03:16.666223

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee7f2a5d3f2a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('active_learning_samples',
    sa.Column('sample_id', sa.UUID(), nullable=False),
    sa.Column('raw_text', sa.String(), nullable=False),
    sa.Column('entities', sa.JSON(), nullable=False),
    sa.Column('is_consumed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('sample_id')
    )
    op.create_table('audit_logs',
    sa.Column('log_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('parser_knowledge_base',
    sa.Column('fingerprint', sa.String(), nullable=False),
    sa.Column('mapping_logic', sa.JSON(), nullable=False),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('discovery_date', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('fingerprint')
    )
    op.create_table('pending_transactions',
    sa.Column('pending_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=True),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('raw_message', sa.Text(), nullable=False),
    sa.Column('sender_name', sa.String(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('transaction_code', sa.String(), nullable=True),
    sa.Column('sender_phone', sa.String(), nullable=True),
    sa.Column('purpose', sa.String(), nullable=True),
    sa.Column('original_ai_output', sa.JSON(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('workflow_status', sa.String(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('source_evidence', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('pending_id'),
    sa.UniqueConstraint('owner_id', 'transaction_code', name='uix_pending_owner_txn_code')
    )
    op.create_table('plans',
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('max_groups', sa.Integer(), nullable=True),
    sa.Column('max_campaigns', sa.Integer(), nullable=True),
    sa.Column('max_transactions_per_month', sa.Integer(), nullable=True),
    sa.Column('price', sa.Integer(), nullable=True),
    sa.Column('allowed_features', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('plan_id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('review_actions',
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('pending_id', sa.UUID(), nullable=True),
    sa.Column('action_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('action_id')
    )
    op.create_table('system_configs',
    sa.Column('config_key', sa.String(), nullable=False),
    sa.Column('config_value', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('config_key')
    )
    op.create_table('users',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('phone_number_verified', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('allow_ai_training', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('preferences', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('phone_number')
    )
    op.create_table('ai_feedback',
    sa.Column('feedback_id', sa.UUID(), nullable=False),
    sa.Column('pending_transaction_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('original_parsed_data', sa.JSON(), nullable=False),
    sa.Column('corrected_data', sa.JSON(), nullable=False),
    sa.Column('is_reviewed', sa.Boolean(), nullable=True),
    sa.Column('is_approved_for_training', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['pending_transaction_id'], ['pending_transactions.pending_id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('groups',
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('group_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('settings_override', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('group_id'),
    sa.UniqueConstraint('owner_id', 'slug', name='uq_group_owner_slug')
    )
    op.create_index(op.f('ix_groups_owner_id'), 'groups', ['owner_id'], unique=False)
    op.create_index(op.f('ix_groups_slug'), 'groups', ['slug'], unique=False)
    op.create_table('notifications',
    sa.Column('notification_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('related_entity_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('notification_id')
    )
    op.create_index('idx_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('idx_notifications_user_id', 'notifications', ['user_id'], unique=False)
    op.create_table('otps',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('identifier', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('subscriptions',
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('plan_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('is_auto_renew', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.plan_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('subscription_id')
    )
    op.create_table('support_tickets',
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_admin_id', sa.UUID(), nullable=True),
    sa.Column('internal_notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['users.user_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('ticket_id')
    )
    op.create_table('token_blacklist',
    sa.Column('token_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('token_id')
    )
    op.create_index(op.f('ix_token_blacklist_token'), 'token_blacklist', ['token'], unique=True)
    op.create_table('usage_tracking',
    sa.Column('usage_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('metric_name', sa.String(), nullable=False),
    sa.Column('current_value', sa.Integer(), nullable=True),
    sa.Column('last_reset', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('usage_id')
    )
    op.create_table('campaigns',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('target_amount', sa.Numeric(), nullable=True),
    sa.Column('payment_instructions', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('slug', sa.String(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('settings_override', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.PrimaryKeyConstraint('campaign_id'),
    sa.UniqueConstraint('group_id', 'slug', name='uq_campaign_group_slug')
    )
    op.create_index(op.f('ix_campaigns_group_id'), 'campaigns', ['group_id'], unique=False)
    op.create_index(op.f('ix_campaigns_slug'), 'campaigns', ['slug'], unique=False)
    op.create_table('subscription_payments',
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subscription_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('provider_reference', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['subscription_id'], ['subscriptions.subscription_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('campaign_report_settings',
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('header_template', sa.String(), nullable=True),
    sa.Column('footer_template', sa.String(), nullable=True),
    sa.Column('use_emojis', sa.Boolean(), nullable=True),
    sa.Column('show_status_text', sa.Boolean(), nullable=True),
    sa.Column('blank_slots_count', sa.Integer(), nullable=True),
    sa.Column('public_access_pin', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ),
    sa.PrimaryKeyConstraint('campaign_id')
    )
    op.create_table('transactions',
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=True),
    sa.Column('transaction_code', sa.String(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('sender_phone', sa.String(), nullable=True),
    sa.Column('sender_name', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('ledger_hash', sa.String(), nullable=True),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('source_evidence', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.campaign_id'], ),
    sa.ForeignKeyConstraint(['group_id'], ['groups.group_id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('transaction_id'),
    sa.UniqueConstraint('owner_id', 'transaction_code', name='uix_owner_txn_code')
    )
    op.create_table('review_allocations',
    sa.Column('allocation_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.UUID(), nullable=False),
    sa.Column('pending_id', sa.UUID(), nullable=True),
    sa.Column('member_name', sa.String(), nullable=True),
    sa.Column('allocated_amount', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.transaction_id'], ),
    sa.PrimaryKeyConstraint('allocation_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review_allocations')
    op.drop_table('transactions')
    op.drop_table('campaign_report_settings')
    op.drop_table('subscription_payments')
    op.drop_index(op.f('ix_campaigns_slug'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_group_id'), table_name='campaigns')
    op.drop_table('campaigns')
    op.drop_table('usage_tracking')
    op.drop_index(op.f('ix_token_blacklist_token'), table_name='token_blacklist')
    op.drop_table('token_blacklist')
    op.drop_table('support_tickets')
    op.drop_table('subscriptions')
    op.drop_table('otps')
    op.drop_index('idx_notifications_user_id', table_name='notifications')
    op.drop_index('idx_notifications_created_at', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_groups_slug'), table_name='groups')
    op.drop_index(op.f('ix_groups_owner_id'), table_name='groups')
    op.drop_table('groups')
    op.drop_table('ai_feedback')
    op.drop_table('users')
    op.drop_table('system_configs')
    op.drop_table('review_actions')
    op.drop_table('plans')
    op.drop_table('pending_transactions')
    op.drop_table('parser_knowledge_base')
    op.drop_table('audit_logs')
    op.drop_table('active_learning_samples')
    # ### end Alembic commands ###
