import base64
import io
from datetime import datetime

try:
    from reportlab.lib.pagesizes import letter
    from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, Image
    from reportlab.lib import colors
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib.enums import TA_CENTER, TA_RIGHT
except ImportError:
    pass

def generate_pdf_report(title: str, total_raised: float, target_amount: float, entries: list, settings: dict = None, tz: str = None, campaign=None) -> str:
    """
    Generates an Enterprise-Grade PDF using ReportLab and returns it as a Base64 string.
    """
    settings = settings or {}
    
    # Process timezone
    from datetime import datetime, timezone
    now_utc = datetime.now(timezone.utc)
    tz = tz or "Africa/Nairobi"
    try:
        from zoneinfo import ZoneInfo
        now_local = now_utc.astimezone(ZoneInfo(tz))
        time_str = now_local.strftime('%d %B %Y at %I:%M %p') + f" ({tz})"
    except Exception:
        time_str = now_utc.strftime('%Y-%m-%d %H:%M:%S UTC')
        
    stream = io.BytesIO()
    doc = SimpleDocTemplate(stream, pagesize=letter)
    elements = []
    
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'MainTitle',
        parent=styles['Title'],
        fontName='Helvetica-Bold',
        fontSize=12,
        textColor=colors.HexColor("#1A5D1A"),
        spaceAfter=12,
        alignment=TA_CENTER
    )
    
    import os
    logo_path = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "assets", "logos", "primary logo.png")
    if os.path.exists(logo_path):
        from reportlab.lib.units import inch
        logo = Image(logo_path, width=2*inch, height=0.6*inch, kind='proportional')
        logo.hAlign = 'CENTER'
        elements.append(logo)
        elements.append(Spacer(1, 12))
    
    from services.reporting.shared import process_template
    
    raw_title = settings.get("report_title", "")
    if campaign:
        display_title = process_template(raw_title, campaign, total_raised)
    else:
        display_title = title
        
    if display_title:
        display_title_html = display_title.replace('\n', '<br/>')
        elements.append(Paragraph(f"<b>{display_title_html}</b>", title_style))
    
    elements.append(Spacer(1, 24))
    
    # 3. Financial Table
    table_data = [["#", "Date", "Name", "Phone", "Amount (KES)", "Method"]]
    from zoneinfo import ZoneInfo
    for idx, txn in enumerate(entries, 1):
        name = txn.sender_name or (f"Member {txn.sender_phone[-4:]}" if txn.sender_phone else "Anonymous")
        
        # Shift transaction time to target timezone
        txn_time = txn.created_at
        if hasattr(txn_time, 'replace'):
            try:
                txn_time = txn_time.replace(tzinfo=timezone.utc).astimezone(ZoneInfo(tz))
            except Exception:
                pass
                
        table_data.append([
            str(idx),
            txn_time.strftime("%Y-%m-%d %I:%M %p"),
            name[:30],
            txn.sender_phone or "-",
            f"{float(txn.amount):,.2f}",
            txn.payment_method or "-"
        ])
        
    try:
        blank_slots = int(settings.get("blank_slots", 0))
    except (ValueError, TypeError):
        blank_slots = 0
        
    for _ in range(blank_slots):
        table_data.append([str(len(table_data)), "", "", "", "", ""])
        
    t = Table(table_data, colWidths=[30, 90, 150, 90, 90, 80])
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor("#1A5D1A")), # KapuLetu Green
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('ALIGN', (4, 1), (4, -1), 'RIGHT'), # STRICT RIGHT ALIGN FOR CURRENCY
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
        ('BACKGROUND', (0, 1), (-1, -1), colors.HexColor("#F0FDF4")), # Zebra stripe 1
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor("#DDDDDD"))
    ]))
    
    # Zebra striping logic
    for i in range(1, len(table_data)):
        if i % 2 == 0:
            t.setStyle(TableStyle([('BACKGROUND', (0, i), (-1, i), colors.white)]))
            
    elements.append(t)
    
    raw_footer = settings.get("report_footer")
    if raw_footer:
        if campaign:
            processed_footer = process_template(raw_footer, campaign, total_raised)
        else:
            processed_footer = raw_footer
        
        if processed_footer:
            elements.append(Spacer(1, 24))
            processed_footer_html = processed_footer.replace('\n', '<br/>')
            elements.append(Paragraph(processed_footer_html, styles['Normal']))
    
    # 4. Footer Branding
    if not settings.get("remove_watermark", False):
        # 9. KapuLetu Branding (Bottom Right)
        branding = Paragraph("<i>Report generated by KapuLetu.</i>", styles['Italic'])
        elements.append(branding)
        
    doc.build(elements)
    
    stream.seek(0)
    pdf_bytes = stream.getvalue()
    
    return base64.b64encode(pdf_bytes).decode('utf-8')
